
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("category/new", "Create category")) ?>
</div>

<?php echo $this->tag->form(array("category/search", "autocomplete" => "off", 'class'=>'form-horizontal')) ?>

    <fieldset>
        <div id="legend" class="">
            <legend class="">Search category</legend>
        </div>
            <div class="control-group">
        <label class="control-label" for="id">Id</label>
        <div class="controls">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
            <p class="help-block">help text</p>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="name">Name</label>
        <div class="controls">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
            <p class="help-block">help text</p>
        </div>
    </div>

        <div class="control-group">
          <div class="controls">
            <?php echo $this->tag->submitButton(array("Search",'class'=>'btn btn-primary')); ?>
          </div>
        </div>
    </fieldset>

</form>
