<?php use Phalcon\Tag; ?>

<?php echo $this->
getContent(); ?>
<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("category/index", "Go Back")); ?></td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("category/new", "Create ")); ?></td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
                        <th>Id</th>
            <th>Name</th>

        </tr>
    </thead>
    <tbody>
        <?php foreach ($page->items as $category) : ?>
        <tr>
                        <td><?php echo $category->id ?></td>
            <td><?php echo $category->name ?></td>

            <td>
                <?php echo $this->tag->linkTo(array("category/edit/" . $category->id, "Edit")); ?>
            </td>
            <td>
                <?php echo $this->tag->linkTo(array("category/delete/" . $category->id, "Delete")); ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td>
                            <?php echo $this->tag->linkTo("category/search", "First") ?></td>
                        <td>
                            <?php echo $this->tag->linkTo("category/search?page=" . $page->before, "Previous") ?>
                        </td>
                        <td>
                            <?php echo $this->tag->linkTo("category/search?page=" . $page->next, "Next") ?>
                        </td>
                        <td>
                            <?php echo $this->tag->linkTo("category/search?page=" . $page->last, "Last") ?>
                        </td>
                        <td>
                            <?php echo $page->current, "/", $page->total_pages ?>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>